- name: Copy mongodb repo file to inside of yumrepos inside the server
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb server (yum package)
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: search and replace mongodb listen address to 0.0.0.0 in mongod.conf file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
