- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove html directory of nginx containing the default html files
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create html directory of files as per project requirement
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download frontend app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf